config/routes.rb
Rails.application.routes.draw do
  
  root "events#index"

  
  
  resources :events do 
    resources :registrations
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord

  has_many :registrations, dependent: :destroy

  validates :name, :location, presence: true
  validates :description, length: { minimum: 25 }
  validates :price, numericality:  { greater_than_or_equal_to: 0 }
  validates :capacity, numericality: { only_integer: true, greater_than: 0 }
  validates :image_file_name, format: { with: /\w+\.(jpg|png)\z/i, 
                                        message: "Must ba a JPG or PNG image" }



  def self.upcoming
    where("starts_at > ?", Time.now).order("starts_at")
  end

  def free?
    price.blank? && price.zero?
  end

  def sold_out?
    (capacity - registrations.size).zero?
  end

end

app/models/registration.rb
class Registration < ApplicationRecord
  
  belongs_to :event

  validates :name, presence: true
  validates :email, format: { with: /\S+@\S+/ }

  HOW_HEARD_OPTIONS = [
    'Newsletter',
    'Blog Post',
    'Twitter',
    'Web Search',
    'Friend/Coworker',
    'Other'
  ]                                        

  validates :how_heard, inclusion: { in: HOW_HEARD_OPTIONS }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.upcoming
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: "Event succesfully updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event , notice: "Event succesfully created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :location, :price, :starts_at, :image_file_name, :capacity)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  before_action :set_event 

  def index
    @registrations = @event.registrations
  end

  def new
    @registration = @event.registrations.new
  end

  def create
    @registration = @event.registrations.new(registration_params)
    if @registration.save
      redirect_to event_registrations_url(@event), notice: "Thank's for registering"
    else
      render :new, status: :unprocessable_entity
    end
  end


  private

  def registration_params
    params.require(:registration).permit(:name, :email, :how_heard)
  end

  def set_event
    @event = Event.find(params[:event_id])    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper

  def price(event)
    if event.free?
      "Free"  
    else
      number_to_currency(event.price, precision: 0)
    end
  end

  def day_and_time(event)
    event.starts_at.strftime("%d/%m/%Y at %H:%M")
  end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper

  def register_or_sold_out(event)
   if event.sold_out?
      content_tag( :span, "Sold Out!", class: "sold-out" )
   else
    link_to "Register", new_event_registration_path(event), class: "register" 
   end
  end

end

app/views/events/_form.html.erb
<%= form_with(model: event) do |f| %>

  <%= render "shared/errors", object: event %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %></div>
  
  <div>
    <%= f.label :location %>
    <%= f.text_field :location %></div>
  
  <div>
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div>
    <%= f.label :starts_at %>
    <%= f.datetime_select :starts_at, {ampm: true}, {class: "datetime"} %>
  </div>

  <div>
    <%= f.label :capacity %>
    <%= f.number_field :capacity %></div>
  
  <div>
    <%= f.label :image_file_name %>
    <%= f.text_field :image_file_name %>
  </div>  

  <div>
    <%= f.submit %>
  </div>

<% end %>

app/views/events/edit.html.erb
  
<h1>Edit <%= @event.name %></h1>

<%= render "form", event: @event %>

 

app/views/events/index.html.erb
<% @events.each do |e|%>
  <section class="event">
    <div class="image">
      <%= image_tag e.image_file_name %>
    </div>
    <div class="summary">
      <h2><%= link_to e.name, e  %></h2>
      <h3><%= day_and_time(e) %> in <%= e.location %></h3>
      <span class="price">
         <%= price(e) %>
      </span>
      <p><%= truncate(e.description, length: 35, separator: ' ')  %></p>
    </div>
  </section>
<% end %>

<section class="admin">
  <%= link_to "Add new event", new_event_path, class: "button" %>
</section>

app/views/events/new.html.erb
<h1>Create a new event</h1>

<%= render "form", event: @event %>
 

app/views/events/show.html.erb
  <section class="event-details">
    <div class="image">
      <%= image_tag @event.image_file_name %>
    </div>
    <div class="details">
      <h1><%= @event.name %></h1>
      <h2><%= pluralize( @event.capacity, "spot" )%> &bull; <%= price(@event) %></h2>
      <h3><%= day_and_time(@event) %> in <%= @event.location %></h3>
      <p><%= @event.description %></p>
      <div class="register">
        <%= register_or_sold_out(@event) %>
        <p>
          <%= link_to "Who is registered?", event_registrations_path(@event)	 %>
        </p>
      </div>
    </div>
  </section>

  <section class="admin">
    <%= link_to "Edit", edit_event_path(@event), class: "button" %>
    <%= link_to "Delete event", @event, class: "button", 
                data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
  </section>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="flash notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="flash notice">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p>
    Made in <a href="https://pragmaticstudio.com"> The Pragmatic Studio </a> 
  </p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <ul>
      <li>
        <%= image_tag("logo.png") %>
      </li>
    </ul>
    <ul>
      <li><%= link_to "Events", events_path %></li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
    
    <%= render "layouts/header" %>

  <body>
    <div class="content"> 
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>

    <%= render "layouts/footer" %>
  </body>

</html>

app/views/shared/_errors.html.erb
  <% if object.errors.any? %>
    <section class="errors">
    <h2>This form could not be saved</h2>
    <h3>
      Please, correct the following
      <%= pluralize(object.errors.size, "error") %>
    </h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>  
    </section>
  <% end %>